backend:
  name: git-gateway
  # use test-repo to view ui changes locally
  branch: main
#publish mode allows control over content publishing enabling review
publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: static/uploads
site_url: https://saltonseascience.org/
logo_url: https://saltonseascience.org/logo-red.png
collections:
  - name: "global"
    label: "Site Settings"
    delete: false
    description: "Settings that are used throughout the entire site"
    extension: "json"
    files:
      - file: "__store__/metadata"
        label: "Metadata"
        name: "site"
        fields:
          - {
              label: "Site Title",
              name: "site_title",
              widget: "string",
              hint: "Used for SEO"
            }
          - {
              label: "Default Site Description",
              name: "default_site_description",
              widget: "text",
              required: false,
              hint: "Used for SEO"
            }
          - { label: "Email", name: "email", widget: "string" }
          - { label: Twitter Url, name: twitter_url, widget: string }
          - { label: Facebook Url, name: facebook_url, widget: string }
          - {
              label: Open Graph Image,
              name: open_graph_image,
              widget: image,
              required: false,
              default: /logo-red.jpg,
              hint: This is the thumbnail that shows up when you share your site on Facebook or via an iMessage
            }

  - name: "pages"
    label: "Pages"
    delete: false
    create: false
    extension: "json"
    files:
      - label: "Home"
        file: "__store__/pages/home"
        extension: "json"
        name: "home"
        fields:
          - label: "Content in English"
            name: "en"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Hero",
                  name: "hero",
                  widget: "string",
                  hint: "Main Home Page Title"
                }
              - {
                  label: "Call to Action",
                  name: "call_to_action",
                  widget: "string",
                  hint: "View Data Button Text"
                }
              - label: "Salton Sea Section"
                name: "salton_sea_section"
                widget: "object"
                collapsed: true
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Content", name: "content", widget: "text" }
              - label: "Metadata"
                name: "metadata"
                widget: "object"
                collapsed: true
                fields:
                  - {
                      label: "Site Title",
                      name: "site_title",
                      widget: "string",
                      hint: "Used for SEO"
                    }
                  - {
                      label: "Default Site Description",
                      name: "site_description",
                      widget: "text",
                      required: false,
                      hint: "Used for SEO"
                    }
                  - {
                      label: "Open Graph Image",
                      name: "open_graph_image",
                      widget: "image",
                      default: "/logo-red.jpg",
                      required: false,
                      hint: "This is the thumbnail that shows up when you share your site on Facebook or via an iMessage"
                    }
                  - {
                      label: "Open Graph Site URL",
                      name: "open_graph_site_url",
                      widget: "string",
                      default: "/logo-red.jpg",
                      required: false,
                      hint: "This is the thumbnail that shows up when you share your site on Facebook or via an iMessage"
                    }
          - label: "Content in Spanish"
            name: "es"
            widget: "object"
            collapsed: true
            fields:
              - {
                  label: "Hero",
                  name: "hero",
                  widget: "string",
                  hint: "Main Home Page Title"
                }
              - {
                  label: "Call to Action",
                  name: "call_to_action",
                  widget: "string",
                  hint: "View Data Button Text"
                }
              - label: "Salton Sea Section"
                name: "salton_sea_section"
                widget: "object"
                collapsed: true
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Content", name: "content", widget: "text" }
              - label: "Metadata"
                name: "metadata"
                widget: "object"
                collapsed: true
                fields:
                  - {
                      label: "Site Title",
                      name: "site_title",
                      widget: "string",
                      hint: "Used for SEO"
                    }
                  - {
                      label: "Default Site Description",
                      name: "site_description",
                      widget: "text",
                      required: false,
                      hint: "Used for SEO"
                    }
                  - {
                      label: "Open Graph Image",
                      name: "open_graph_image",
                      widget: "image",
                      default: "/logo-red.jpg",
                      required: false,
                      hint: "This is the thumbnail that shows up when you share your site on Facebook or via an iMessage"
                    }
                  - {
                      label: "Open Graph Site URL",
                      name: "open_graph_site_url",
                      widget: "string",
                      default: "/logo-red.jpg",
                      required: false,
                      hint: "This is the thumbnail that shows up when you share your site on Facebook or via an iMessage"
                    }
